dew:
  cluster:
    cache: redis
    mq: redis

management:
  security: false
  context-path: /management-admin

endpoints:
  restart:
    enable: true


logging:
  path: ./logs
  level:
    com:
      zt:
        scala: DEBUG

spring:
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB



scala:
  hdfs:
    originPath: /User/zt/scala
    destinationPath: /test
    hdfsUri: hdfs://139.219.67.133:9000
